{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name | default .Release.Namespace }}
  labels:
    {{- include "traffic-capture.labels" . | nindent 4 }}
    {{- if .Values.namespace.labels }}
    {{- toYaml .Values.namespace.labels | nindent 4 }}
    {{- end }}
    {{- if .Values.namespace.enableIstioInjection }}
    istio-injection: enabled
    {{- end }}
  {{- if .Values.namespace.annotations }}
  annotations:
    {{- toYaml .Values.namespace.annotations | nindent 4 }}
  {{- end }}
{{- end }}